services:
  dr_backend:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: dr_backend
    restart: always
    ports:
      - "8558:${APP__PORT}"
    env_file:
      - ./backend/.env
